#!/bin/bash -l
#
#SBATCH --job-name Test_NN_512x512_1gpu_v03
#SBATCH --output out/%x-cont.out%j
#SBATCH --nodes 1
#SBATCH --partition timed-gpu
#SBATCH --gres gpu:1
#
# This is a basic example of running a GPU job
# to train a neural network model using Keras
# and TensorFlow.
#
# This script is configured to run on ODU's Wahab and Turing clusters.
# Running the same training on other cluster will require adjustments
# on this script.
#

module load container_env tensorflow-gpu/2.6.0

# Optional: Show the SLURM variables for debugging
export | grep '^declare -x SLURM_'
echo
module list

echo 'Using official tensorflow-gpu'
time  crun.tensorflow-gpu  python3  Test_NN_512x512_1gpu_v03.py
